# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: CI / CD

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main

env:
  TAG: $(echo ${{ github.sha }} | cut -c1-8)
  PREVIEW_URL: travel-blog-pr-${{ github.event.pull_request.number }}.preview.eden-reich.com
  APP_NAME: travel-blog
  APP_DISPLAY_NAME: Travel Blog

jobs:
  build:
    name: Build container image
    runs-on:
      - self-hosted
      - k8s
    steps:
      - name: Checkout ${{ env.APP_NAME }} repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: edenreich
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build container image
        run: |
          TAG=${{ env.TAG }} make package

      - name: Push container image to ghcr.io
        run: |
          TAG=${{ env.TAG }} make push

  create_preview_environment:
    name: Create preview environment
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    needs: build
    environment:
      name: preview
      url: https://${{ env.PREVIEW_URL }}
    runs-on:
      - self-hosted
      - k8s
    steps:
      - name: Checkout infrastructure repository
        uses: actions/checkout@v3
        with:
          repository: edenreich/infrastructure
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Create ArgoCD Application
        run: |
          cat <<-EOF > argocd/01-clusters/staging/${{ env.APP_NAME }}-preview-pr-${{ github.event.pull_request.number }}.yaml
          # This file was auto-generated by the CI pipeline in the ${{ env.APP_NAME }} repository.
          ---
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ${{ env.APP_NAME }}-preview-environment-pr-${{ github.event.pull_request.number }}
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
            labels:
              app.kubernetes.io/name: ${{ env.APP_NAME }}-preview-environment-${{ github.event.pull_request.number }}
              app.kubernetes.io/part-of: ${{ env.APP_NAME }}
          spec:
            project: staging
            source:
              repoURL: ${{ github.server_url }}/${{ github.repository }}.git
              targetRevision: ${{ github.head_ref }}
              path: helm
              helm:
                parameters:
                  - name: image.tag
                    value: "${{ env.TAG }}"
                  - name: ingress.enabled
                    value: "true"
                  - name: ingress.hosts[0].host
                    value: ${{ env.PREVIEW_URL }}
                  - name: ingress.hosts[0].paths[0].path
                    value: /
                  - name: ingress.hosts[0].paths[0].pathType
                    value: Prefix
                  - name: ingress.hosts[0].paths[0].backend.service.name
                    value: ${{ env.APP_NAME }}
                  - name: ingress.hosts[0].paths[0].backend.service.port.number
                    value: "8080"
            destination:
              namespace: ${{ env.APP_NAME }}-preview-environment-pr-${{ github.event.pull_request.number }}
              name: staging
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
          EOF
          git diff --color main

      - name: Push ArgoCD Application
        run: |
          git config --global user.email "${{ env.APP_NAME }}@eden-reich.com"
          git config --global user.name "${{ env.APP_DISPLAY_NAME }}"
          git add argocd/01-clusters/staging/${{ env.APP_NAME }}-preview-pr-${{ github.event.pull_request.number }}.yaml
          git commit -m "Add preview environment for PR #${{ github.event.pull_request.number }}"
          git push origin main

  deploy:
    name: Deploy to production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build
    environment:
      name: production
      url: https://${{ env.APP_NAME }}.eden-reich.com
    runs-on:
      - self-hosted
      - k8s
    steps:
      - name: Checkout ${{ env.APP_NAME }} repository
        uses: actions/checkout@v3
        with:
          repository: edenreich/infrastructure
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Patch ArgoCD Application
        run: |
          cat <<-EOF > argocd/01-clusters/production/${{ env.APP_NAME }}.yaml
          # This file was auto-generated by the CI pipeline in the ${{ env.APP_NAME }} repository.
          ---
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ${{ env.APP_NAME }}
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
            labels:
              app.kubernetes.io/name: ${{ env.APP_NAME }}
              app.kubernetes.io/part-of: ${{ env.APP_NAME }}
          spec:
            project: production
            source:
              repoURL: ${{ github.server_url }}/${{ github.repository }}.git
              targetRevision: main
              path: helm
              helm:
                parameters:
                  - name: image.tag
                    value: "${{ env.TAG }}"
                  - name: ingress.enabled
                    value: "true"
                  - name: ingress.hosts[0].host
                    value: ${{ env.APP_NAME }}.eden-reich.com
                  - name: ingress.hosts[0].paths[0].path
                    value: /
                  - name: ingress.hosts[0].paths[0].pathType
                    value: Prefix
                  - name: ingress.hosts[0].paths[0].backend.service.name
                    value: ${{ env.APP_NAME }}
                  - name: ingress.hosts[0].paths[0].backend.service.port.number
                    value: "8080"
            destination:
              namespace: ${{ env.APP_NAME }}
              name: production
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
          EOF

      - name: Push ArgoCD Application
        run: |
          git config --global user.email "${{ env.APP_NAME }}@eden-reich.com"
          git config --global user.name "${{ env.APP_DISPLAY_NAME }}"
          git add argocd/01-clusters/production/${{ env.APP_NAME }}.yaml
          git commit -m "Bump ${{ env.APP_NAME }} production version to ${{ env.TAG }}"
          git push
