# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Cleanup Preview Environment

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  APP_NAME: travel-blog
  APP_DISPLAY_NAME: Travel Blog

jobs:
  teardown_preview_environment:
    name: Teardown Preview Environment
    environment: preview
    runs-on:
      - self-hosted
      - k8s
    steps:
      - name: Checkout infrastructure repository
        uses: actions/checkout@v3
        with:
          repository: edenreich/infrastructure
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Delete ArgoCD Application
        run: |
          git config --global user.email "${{ env.APP_NAME }}@eden-reich.com"
          git config --global user.name "${{ env.APP_DISPLAY_NAME }}"
          git rm -f argocd/01-clusters/staging/${{ env.APP_NAME }}-preview-pr-${{ github.event.pull_request.number }}.yaml
          git commit -m "Delete ${{ env.APP_NAME }} preview environment for PR #${{ github.event.pull_request.number }}"
          git push
